version: "3"
services:
  autosub:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLI_ARGS= --engine ds
                  --port 5000
                  --model models/deepspeech-0.9.3-models.pbmm
                  --scorer models/deepspeech-0.9.3-models.scorer
    container_name: AutoSub-WebAPI
    volumes:
      - ./uploads:/app/uploads
      - ./audio:/app/audio
      - ./output:/app/output
    ports:
      - 5000:5000